version: '3.1'

services:

  redis_db:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
